export const SEND_MESSAGE = "SEND_MESSAGE";
export const SHOW_USER_MESSAGE = "SHOW_USER_MESSAGE";
export const UPDATE_CONVERSATION_CONTEXT = "UPDATE_CONVERSATION_CONTEXT";
export const SWITCH_USER_INPUT = "SWITCH_USER_INPUT";